import './globals.css'

import { Inter } from 'next/font/google'
import Menu from '@/app/components/Menu'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const data = [
  {
    label: 'Menu 1',
    children: [
      {
        label: 'login',
        link: '/login',
      },
      {
        label: 'Submenu 1.2',
        children: [
          {
            label: 'Submenu 1.2.1',
            link: '/login',
          },
          {
            label: 'Submenu 1.2.2',
            link: '/login',
          },
        ],
      },
    ],
  },
  {
    label: 'Menu 2',
    children: [
      { label: 'Submenu 2.1' },
      { label: 'Submenu 2.2' },
    ],
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu data={data} firstChild={true} />
        {children}
      </body>
    </html>
  )
}
